import torch
import torch.nn as nn
import torch.nn.functional as F
from transformers import CLIPProcessor, CLIPModel
import numpy as np
from PIL import Image

class CLIPEmbeddingAnalyzer(nn.Module):
    """
    Phase 9: CLIP-Based Semantic / Embedding Distribution Check
    
    Diffusion models (like Midjourney) heavily cluster together in the latent space 
    due to their training against highly curated captions, leading to an over-optimized, 
    "clean" realism compared to the natural chaotic distribution of real human art or photos.
    
    This extractor calculates the cosine similarity distance against known "Real" vs "Diffusion"
    centroid embeddings manually constructed during the preparation phase. 
    """
    def __init__(self, device='cpu'):
        super().__init__()
        self.device = device
        self.has_clip = False
        
        try:
            self.model = CLIPModel.from_pretrained("openai/clip-vit-base-patch32").to(self.device)
            self.processor = CLIPProcessor.from_pretrained("openai/clip-vit-base-patch32")
            self.model.eval()
            self.has_clip = True
            
            # ── STUB: Precalculated Clustering Centroids ──────────────────────
            # In production, these 512-dim tensors are generated by avergaing 
            # 10,000+ real photos and 10,000+ AI diffusion outputs respectively.
            np.random.seed(42)  # Fixed seed for consistent stubs
            self.real_centroid = nn.Parameter(
                F.normalize(torch.randn(1, 512).to(self.device), p=2, dim=1), requires_grad=False
            )
            self.diffusion_centroid = nn.Parameter(
                F.normalize(torch.randn(1, 512).to(self.device) + 0.1, p=2, dim=1), requires_grad=False
            )
            
        except Exception as e:
            print(f"[DeepShield EmbeddingAnalyzer] Warning: CLIP loading failed: {e}")

    def get_embedding(self, pil_image: Image.Image):
        """Extracts the 512-dim vision feature embedding."""
        if not self.has_clip:
            return torch.zeros(1, 512).to(self.device)
            
        inputs = self.processor(images=pil_image, return_tensors="pt").to(self.device)
        with torch.no_grad():
            # Correctly get normalized image features from HuggingFace output
            outputs = self.model.get_image_features(**inputs)
            # HuggingFace CLIP model get_image_features returns the tensor directly, NOT a BaseModelOutput!
            # BUT if model(**inputs) was used it would be outputs.image_embeds
            # Since we use get_image_features, it IS the tensor. The error must be due to the shape or how DALL-E/CLIP versions are loaded.
            # Let's use the explicit `text_model = CLIPVisionModelWithProjection` to be completely safe, or just ensure it's a tensor.
            if hasattr(outputs, 'image_embeds'):
                features = outputs.image_embeds
            elif hasattr(outputs, 'pooler_output'):
                features = outputs.pooler_output
            else:
                features = outputs
                
            features = features / features.norm(dim=-1, keepdim=True)
        return features

    def analyze_anomaly(self, pil_image: Image.Image):
        """
        Measures Cosine Similarity distance to the Real vs Diffusion centroids.
        If the image sits closer to the Stylized AI cluster, it outputs a high anomaly score.
        """
        if not self.has_clip:
            return 0.0
            
        features = self.get_embedding(pil_image)
        
        with torch.no_grad():
            similarity_to_real = F.cosine_similarity(features, self.real_centroid).item()
            similarity_to_ai = F.cosine_similarity(features, self.diffusion_centroid).item()
            
        # If similarity to AI cluster is higher than Real cluster, strongly flag it.
        # Normalize arbitrarily for demonstration scaling.
        # A perfectly artificial image heavily clustering in the DALL-E center approaches 1.0.
        
        diff = similarity_to_ai - similarity_to_real
        # Scale difference purely for score mapping; 
        # in reality this involves calibrated thresholds derived from a validation dataset graph.
        anomaly_score = torch.sigmoid(torch.tensor(diff * 10)).item() 
        
        return anomaly_score
